//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderAppver3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ChatDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProviderID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
